
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
        docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

    - name: Build Docker imaname: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # -----------------------------
    # Configure AWS credentials
    # -----------------------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: ${{ secrets.AWS_SECRET_REGION }}

    # -----------------------------
    # Login to AWS ECR
    # -----------------------------
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_SECRET_REGION }} | \
        docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_POD16 }}

    # -----------------------------
    # Build Docker Image
    # -----------------------------
    - name: Build Docker image
      run: |
        docker build -t pod16app .

    # -----------------------------
    # Tag Image for ECR
    # -----------------------------
    - name: Tag Docker image
      run: |
        docker tag pod16app:latest ${{ secrets.ECR_REPO_POD16 }}:latest

    # -----------------------------
    # Push to ECR
    # -----------------------------
    - name: Push Docker to ECR
      run: |
        docker push ${{ secrets.ECR_REPO_POD16 }}:latest

    # -----------------------------
    # Copy SSH key to runner
    # -----------------------------
    - name: Create SSH Key
      run: |
        echo "${{ secrets.SSH_KEY_PEM }}" > key.pem
        chmod 600 key.pem

    # -----------------------------
    # Deploy to EC2 via SSH
    # -----------------------------
    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.SECRET_IP_ADDRESS }} << 'EOF'
          echo "Logging into ECR..."
          aws ecr get-login-password --region ${{ secrets.AWS_SECRET_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_POD16 }}

          echo "Pulling latest image..."
          docker pull ${{ secrets.ECR_REPO_POD16 }}:latest

          echo "Stopping old container..."
          docker stop pod16app || true
          docker rm pod16app || true

          echo "Running new container..."
          docker run -d --name pod16app -p 3000:3000 ${{ secrets.ECR_REPO_POD16 }}:latest

          echo "Deployment complete!"
        EOF

